apiVersion: v1
kind: Service
metadata:
  name: trackheatmap
  labels:
    app: trackheatmap
    vendor: kibernetika
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  - port: {{ .Values.service.rtmp.port }}
    targetPort: 1935
    protocol: TCP
    name: rtmp
  selector:
    app: trackheatmap
    vendor: kibernetika