Image:
  Name: kuberlab/realtimeheatmap
  Tag: 1.0.4

service:
  type: NodePort
  http:
    port: 8000
  rtmp:
    port: 1935

ingress:
  enabled: false
  annotations: {}
    hosts:
      - host: heatmap.local
        paths: []
    tls: []

resources:
  requests:
    cpu: "100m"
    memory: "128M"
    hddl: "8"
  limits:
    cpu: "8"
    memory: "16G"

env:
  - name: STREAM_COUNT
    value: "16"
  - name: TRACKHEATMAP
    value: "yes"
  - name: RUNTIME_HEATMAP
    value: "yes"
  - name: MULTIDETECT
    value: "1"
  - name: OUTPUT
    value: "mjpg"
  - name: RTMP_BACKEND
    value: srs

useHDDL: false
runOnVCANode: false
